@startuml design

left to right direction

class User{
    -id: Int
    -name: String
    -password: String
    -creation_date: String
}

class Customer_User{
    +place_order: String
    +track_order: String
}

class Product{
    -code: Int
    -description: String
    -availability: Boolean
    -price: Int
}

class Order{
    -number: Int
    -creation_date: String
    -items: String
    -status: String
}

class Item{
    -sequential_number: Int
    -quantity: Int
    -paid_price: Double 
}

class Administrator{
    +change_order_status
    +update_products_catalog
}

User --|> Customer_User
User --|> Administrator 
Customer_User "1"--"many" Order
Product -- Item
Order . Product 
@enduml