@startuml design

left to right direction

class User{
    -authenticate: String 
}

class Customer_User{
    +place_order: String
    +track_order: String
}

class Product{

}

class Order{

}

class Item{

}

class Administrator{
    +change_order_status
    +update_products_catalog
}

User *--> Customer_User
Customer_User -- Order
Product -- Item
Order . Product 
@enduml