@startuml Use_Case

left to right direction

:customer_user:
:user:
:administrator:
package system{
    (authenticate)
    (place orders)
    (track orders)
    (change order status)
    (update products catalog)
    (order status)
}
:user: ..> (authenticate) : User Info
:customer_user: --|> :user:
:customer_user: --> (place orders)
:customer_user: --> (track orders)

:administrator: --> (change order status)
:administrator: --> (update products catalog)
:administrator: --|> :user:
(change order status) ..> (order status) : updates
(place orders) ..> (order status) : updates
(track orders) ..> (order status) : views



@enduml